### ISSUE TITLE
Correção 

### ISSUE THREAD

**Issue by 0arKes** [ATCo-alexandre/game-yu#1]
Opa @ATCo-alexandre Tudo bom ?
Sou o Bruno, vi seu post no fórum da dio :)
Acredito que, o problema que esteja acontecendo, seja por conta das aspas na chamada #drawCads

Se liga:
```
function init() {
drawCards(5, playerSides.player1);   // -> Sem aspas
drawCards(5, playerSides.computer);   // -> Sem aspas
}
```
Tenta ai, que qualquer coisa tento te ajudar de outra maneira.
Abrax

**Comment by ATCo-alexandre** [comment]
Boa noie, Sr Bruno. Já corrigi o problema. Muito obrigado.
Boa noite.

**Comment by ATCo-alexandre** [comment]
Erro corrigido
